### ISSUE TITLE
User Logins

### ISSUE THREAD

**Issue by SarahSparky** [reprogamaco/fb-phish#1]
I'm having problems geting the user logins. I know you say on the bottom of the page is a box but I don't see that at all. I'm using it in the windows version of kali linux. I just see the constant scrolling of information.

**Comment by reprogamaco** [comment]
The box is in the footer, look beside the chinese language, you will see the box. 

Look a demo:
![Screenshot from 2024-02-15 05-22-37](https://github.com/reprogamaco/fb-phish/assets/76619967/abe1ae13-899a-4d54-a0bf-3cfacd113137)

Now by clicking the box shown, you will be redirected to the page showing the people passwords and usernames
